### ISSUE TITLE
好像失效了。。

### ISSUE THREAD

**Issue by cxhttt233** [zhongfly/ASF-Railway#1]

**Comment by zhongfly** [comment]
请提供详细的错误日志
另：我现在已经没有railway的账号，无法测试在railway上是否正常，但我通过其他方法测试正常。
请检查是否按照asf的需要添加了asf的设置文件，本项目并不是开箱即用，建议现在本地学习/熟悉asf的各项设置/操作，确保能在本地成功运行asf后再使用。

**Comment by cxhttt233** [comment]
之前成功过，一直稳定运行，突然失效了

我原来的项目显示
![image](https://user-images.githubusercontent.com/28983554/188127427-6fa5d189-f89d-4c57-9526-e1d15f4fa89a.png)

然后重新部署railway显示

You are currently viewing a legacy template. Support for legacy templates will be discontinued at the end of August. If you are the owner of this template, please re-create this template using our [new template system](https://railway.app/button).

您当前正在查看旧版模板。对传统模板的支持将于8月底停止。如果您是此模板的所有者，请使用我们的新模板系统重新创建此模板。
![image](https://user-images.githubusercontent.com/28983554/188127065-2da6ecc8-0a83-4ef6-a74c-087a295b92ee.png)

![image](https://user-images.githubusercontent.com/28983554/188127263-f0fd7d90-50ed-4013-b834-171d5dea485a.png)
不是是不是这个的问题，我再试试

**Comment by zhongfly** [comment]
是railway那边的变化啊…主要是我现在没帐号了，也测试不了，只能我这边修改了，找你测试

**Comment by zhongfly** [comment]
![Screenshot_20220902193500](https://user-images.githubusercontent.com/11155705/188131231-41423ce8-5cb2-4672-abad-277f789890df.png)
这一项里像这样填 你账户里之前创建的这个项目地址 (或者 https://github.com/zhongfly/ASF-Railway/generate 用模板生成一个你的项目，勾选private)，其他地方随便编个名字

还要添加一个环境变量
![Screenshot_20220902194458](https://user-images.githubusercontent.com/11155705/188132788-6cbd083b-1f90-4056-b7df-509382c34f6b.png)
填完点右下角的add variable保存

这样试试吧

**Comment by zhongfly** [comment]
试试这个按钮
[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/new/template/kSdMwJ)

**Comment by cxhttt233** [comment]
好像明白了，是因为之前的模板过期了，需要重新生成一份

按照你的指导
![1](https://user-images.githubusercontent.com/28983554/188256939-ccf7d4f6-5204-4c90-b6ba-9924bfc04cc1.png)
这样就生成了正确的模板，点击模板，创建项目

![2](https://user-images.githubusercontent.com/28983554/188257068-c506a3e4-484f-499d-8b97-18b8a44b20c8.png)

后面的操作就跟之前一样了
![3](https://user-images.githubusercontent.com/28983554/188257003-507282f8-ccf7-4ed4-8891-ca422f36d8e8.png)
正常工作，十分感谢
![4](https://user-images.githubusercontent.com/28983554/188257079-e821358c-f8d4-4c7f-b8ad-068f87ff4889.png)
